server:
  port: 3001

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/questionnaire?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2002gzh...

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gzh.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

questionnaire:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: questionnaire
    # 设置jwt过期时间 2h
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: Authorization